config/routes.rb
Rails.application.routes.draw do

  scope path_names: {new: 'nowe'} do
    resources :confessions, path: 'wyznania' do
      collection do
        get 'special'
      end
    end
  end

  root 'confessions#special'

end

app/models/confession.rb
class Confession < ActiveRecord::Base


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confessions_controller.rb
class ConfessionsController < ApplicationController

  def special
    @confession = Confession.last
    if @confession.nil?
      render 'static/index'
    end
  end

  def index
    @confessions = Confession.all.order(created_at: :desc)
  end

  def new
    @confession = Confession.new
  end

  def create
    @confession = Confession.new confession_params
    if @confession.save
      flash[:notice] = "Twoje wyznanie zostało zapisane"
      redirect_to confessions_path
    else
      flash[:error] = "Popraw błedy i spróbuj ponownie"
      render action: "new"
    end

  end


  private
    def confession_params
      params.require(:confession).permit(:title, :description, :author, :location, :gender)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confessions_helper.rb
module ConfessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/confessions/index.html.haml
%div.page-header
  %h1 Dzisiejsze wyznania
  %nav
    = link_to "+ dodaj wyznanie", new_confession_path, class: 'btn btn-primary'
%div.page-content
  - if @confessions.size > 0
    - @confessions.each do |c|
      %div.well
        - unless c.title.blank?
          %h3= c.title
        = simple_format c.description
        %p.author
          = "#{distance_of_time_in_words_to_now c.created_at} temu"
          &mdash;
          - if c.author.blank?
            Anonimowe
          - else
            = c.author
    = link_to "Dodaj własne wyznanie", new_confession_path, class: 'btn btn-primary'
  - else
    %p Nikt nie dodał jeszcze wyznania. Odważysz się?

app/views/confessions/new.html.haml
%div.page-header
  %h1 Nowe wyznanie

%div.page-content
  = form_for [@confession] do |f|

    .form-group
      = f.label :title, "Tytuł (opcjonalny):"
      = f.text_field :title, class: 'form-control', autofocus: true
      %span.help-block Jeśli nie chcesz nadawać tytułu, po prostu zostaw puste pole

    .form-group
      = f.label :description, "Treść:"
      = f.text_area :description, class: 'form-control', rows: 8
      %span.help-block Wulgaryzmy, groźby, skrajne przejawy nietolerancji i rasizmu nie będą tolerowane.<br/>Zabronione jest również publikowanie danych osobowych oraz informacji umożliwiających identyfikację osób w serwisie.

    .form-group
      = f.label :author, "Podpis (opcjonalny):"
      = f.text_field :author, class: 'form-control', autofocus: true, placeholder: "To może być Twój pseudonim, imię, inicjały..."
      %span.help-block Pamiętaj, aby nie zdradzać toższamości!

    .actions
      = f.submit 'Dodaj wyznanie', class: "btn btn-primary btn-lg"

app/views/confessions/special.html.haml
- content_for :hero do
  %div.secret
    - unless @confession.title.blank?
      %h1= @confession.title
    = simple_format @confession.description

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_footer.html.haml
%footer.site-footer
  %div.container
    %p &copy; 2014-2015 &mdash; Anonimowe-Wyznania.pl

app/views/layouts/_header.html.haml
%header.site-header
  = link_to root_path, class: 'page-logo' do
    Anonimowe Sekrety
  %p Możesz tu bez obaw możesz podzielić się swoimi wyznaniami i sekretami.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Anonimowe sekrety, wyznania i konwersacje na Anonimowe-Sekrety.pl
    %meta{name: 'description', content: 'Dziel się sekretami i anonimowymi informacjami. Znajdź wyznania nieznajomych, zobacz czy jest coś ciekawego dla Ciebie. 100% dyskrecji!'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if Rails.env == 'production'
      = render partial: 'layouts/gat'
    = render partial: 'layouts/header'

    - if content_for? :hero
      = yield :hero

    %div.container
      = render partial: 'layouts/flash'
      = yield

    = render partial: 'layouts/footer'